language: python
python:
  - "3.3"
  - "3.5"
  - "3.6"

install:
  - pip install prettytable
  - pip install DateTime


notifications:
  slack: ssw555-workspace:BQrt2tCt6OUZdLAyHteMRGW3

script:
  - unit_test.py

